apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderprocessor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderprocessor
  template:
    metadata:
      labels:
        app: orderprocessor
    spec:
      containers:
        - name: orderprocessor
          image: registry.local:5000/orderprocessor:20250908043241   # <-- Update this tag when needed
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://192.168.0.243:31432/erp
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
