apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  username: <your_postgres_user>
  password: <your_postgres_password>
  database: <your_postgres_db>
